apiVersion: v1
kind: Pod
metadata:
  name: myapp-deployment
  labels:
    name: myapp-deployment
spec:
  containers:
  - name: myapp
    image: aleferreiranogueira/k8s-training-app:0.1
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    ports:
      - containerPort: 8080
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: name
                  operator: In
                  values:
                    - "myapp"
            topologyKey: "kubernetes.io/hostname"
          weight: 1
