apiVersion: v1
kind: Pod
metadata:
  name: app03
  namespace: k8s-training
  labels:
    name: app03
spec:
  containers:
  - name: app03
    image: aleferreiranogueira/k8s-training-app:0.3
    ## 3) ConfigMap
    env:
      - name:  API_HOST
        valueFrom:
          configMapKeyRef:
            name:  app01-cm
            key:  API_HOST
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "64Mi"
        cpu: "100m"
    ports:
      - containerPort: 8080
