apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
  namespace: k8s-training
spec:
  ## 1) Replicas
  replicas: 1
  selector:
    matchLabels:
      name: app01
  template:
    metadata:
      labels:
        name: app01
    spec:
      containers:
      - name: myapp
        image: aleferreiranogueira/k8s-training-app:0.3
        ## 2) recursos
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        ## 3) HA - probes
        livenessProbe: # Quando restartar o pod
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        # 4) ConfigMap
        envFrom:
          - configMapRef:
              name: app01-cm